name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@v1

      - name: Build Docker image
        uses: useblacksmith/build-push-action@v2
        with:
          context: .
          push: false
          tags: teamsync:test
